### PR TITLE
Used cmake eclass instead of cmake-utils. Fixed MY_PV var.

### PR DESCRIPTION
**Pull request by anex5**
Able to build latest blender.

### CODE REVIEW

**Comment by brothermechanic** [comment]
Wait wait, let's talk
You have god dev temp
I describe why i turn cmake-utils back
With cmake (and may be ninja) i got error
`GPU_vertex_buffer.h:121:22: error: ‘GPUVertBufRaw’ {aka ‘struct GPUVertBufRaw’} has no member named ‘_data_end’`
https://gist.github.com/brothermechanic/011b300a34a7248a0d70b898dac137fb
May be you want to find problem and after that turn cmake+ninja back, but with cmake-utils all fine
Have you problem with cmake-utils?

**Comment by brothermechanic** [comment]
Looks like you fix 
grep: /CPackConfig.cmake: No such file or directory

**Comment by brothermechanic** [comment]
If you have power and time to code 
for now main aim of blender ebuild (gentoo official ebuild too) - to unbound external libs from blender distro
* Remaining bundled dependencies:
 * - extern/curve_fit_nd
 * - extern/xdnd
 * - extern/glew
 * - extern/cuew
 * - extern/sdlew
 * - extern/wcwidth
 * - extern/ceres
 * - extern/draco
 * - extern/clew
 * - extern/audaspace
 * - extern/quadriflow
 * - extern/rangetree
 * - extern/glog
 * - extern/bullet2
 * - extern/lzma
 * - extern/gmock
 * - extern/mantaflow
 * - extern/binreloc
In ideal world this libs must be by system, not in boundle)))

**Comment by anex5** [comment]
Previously I had the same error with the latest build, but this error never happend on stable version. So I think, this error is not related to [cmake-utils](https://devmanual.gentoo.org/eclass-reference/cmake-utils.eclass). It seems like improper **src_prepare** function or outdated dependencies cause this error. Yestoday I've managed to build latest version with **no errors** with cmake eclass. You can check it by yourself before merging pull request.

**Comment by anex5** [comment]
I figured out that following error, is appears only when variable CMAKE_BUILD_TYPE="Release" is not set.
`GPU_vertex_buffer.h:121:22: error: ‘GPUVertBufRaw’ {aka ‘struct GPUVertBufRaw’} has no member named ‘_data_end’`

Please check it by yourself and merge this pull request.

**Comment by brothermechanic** [comment]
Hello
I make moving to cmake eclass with CMAKE_BUILD_TYPE="Release" by myself
For now master go forward, and now i cannot merge your pull
stay tunned!

**Pull request closed without merging**
