### PR TITLE
updated the latest version in git

### PR DESCRIPTION
**Pull request by kalmarek**
These (fairly trivial) changes the last revisions of AB compile and install.
I know it's not the gentoo way to pull and compile two packages at once (i.e. Qtnproperty), but...
(I see You're ebuilding the QtnProperty already)

### CODE REVIEW

**Comment by brothermechanic** [comment]
Hello
I have a problem with compiling live version of AB?
Can you try to build it?

**Comment by brothermechanic** [comment]
Hello
Do you have sussesfully compiled latest AB?

**Comment by kalmarek** [comment]
just now

**Comment by kalmarek** [comment]
Some icons have moved, I see...

**Comment by brothermechanic** [comment]
Good. Can you give me last your ebuild?

**Comment by brothermechanic** [comment]
Thanks! Works!
How about this icons? http://wstaw.org/m/2016/05/11/plasma-desktopRs4864.png

**Comment by kalmarek** [comment]
You mean they're unreadable? that's an issue for the designer;
The general UI of this program sucks ;-) 
(and hardcoding/using non-standard fonts sucks even more)

**Comment by kalmarek** [comment]
Try the ebuild with the gl330 flag

**Comment by brothermechanic** [comment]
I found that some bugs happened because AB can't write the config/ini file http://wstaw.org/m/2016/05/11/plasma-desktopFR4864.png
I wrote to developer about that

**Pull request closed without merging**
