### PR TITLE
Candidate 1.2.1 ebuild for OIDN

### PR DESCRIPTION
**Pull request by Cheaterman**
Everything in the title. Git version was failing to merge for me with some LFS-related issues, so I made this instead.

I hope you like it!

### CODE REVIEW

**Comment by brothermechanic** [comment]
Thank you very much!

**Comment by brothermechanic** [comment]
This is happens because portage don't supported git lfs ((((

**Comment by brothermechanic** [comment]
Hello again,
i try to test your ebuild, but get trouble with dev-lang/ispc (gentoo version depend very old llvm)
i try to create new live ebuild, but can't finished it
Can you help to tune dev-lang/ispc?

**Comment by Cheaterman** [comment]
Hello @brothermechanic !

I'm sorry I totally forgot - https://bugs.gentoo.org/729924 this is in the works.

I'm going to make a PR to add this to ::cg immediately. Thanks for the reminder, and sorry for my omission!

**Comment by brothermechanic** [comment]
Wow!
Super!
Thank you

**Pull request merged**
